<?php

/**
 * the main administration function
 *
 * @return       output       The main module admin page.
 */
function UserDeletion_admin_main()
{
    // Security check
    if (!pnSecAuthAction(0, 'UserDeletion::', '::', ACCESS_EDIT)) {
        return pnVarPrepHTMLDisplay(_MODULENOAUTH);
    }

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $pnRender =& new pnRender('UserDeletion');

    $action=pnVarCleanFromInput('action');
    if (isset($action) && ($action == 'update')) {
	$email_submitted=pnVarCleanFromInput('email');
	if (!isset($email_submitted)) $email='';
	else $email=$email_submitted;
	pnModSetVar('UserDeletion','email',$email);
	pnSessionSetVar('statusmsg',_USERDELETIONUPDATED);
    }

    // Return the output that has been generated by this function
    return $pnRender->fetch('userdeletion_admin_main.htm');
}


?>