<?php

/**
 * the main administration function
 *
 * @return       output       The main module admin page.
 */
function UserDeletion_admin_main()
{
    // Security check 
    if (!SecurityUtil::checkPermission('UserDeletion::', '::', ACCESS_ADMIN)) return LogUtil::registerPermissionError();

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render				= pnRender::getInstance('UserDeletion');
	// get parameters
    $action				= FormUtil::getPassedValue('action');
    $uname				= FormUtil::getPassedValue('uname','','POST');
    $uid				= FormUtil::getPassedValue('uid',0,'GET');
	$email_submitted 	= FormUtil::getPassedValue('email');

	if (isset($action) && !SecurityUtil::confirmAuthKey()) LogUtil::registerAuthIDError();
    else if (isset($action) && ($action == 'email')) {
		if (!isset($email_submitted)) $email='';
		else $email=$email_submitted;
		// set new email adress
		pnModSetVar('UserDeletion', 'email', $email);
		LogUtil::registerStatus(_USERDELETIONUPDATED);
    }
    else if (isset($action) && ($action == 'delete')) {
      	if ($uid > 1) {
      	  	// we'll use the user part of this module so we have to laod the language files
      	  	pnModLangLoad('UserDeletion','user');
		    // call the delete-function
		    $output = pnModAPIFunc('UserDeletion','user','delete',array('uid' => $uid));
		
		    // create output
		    $render = pnRender::getInstance('UserDeletion');
			
			// assign data
			$render->assign('output',	$output);
			$render->assign('admin',	1);
			
		    // Return the output that has been generated by this function
		    return $render->fetch('userdeletion_user_result.htm');
		 	   
		}
		else {
	      	$uid = pnUserGetIDFromName($uname);
	      	if ($uid > 0) {
		      	$render->assign('uid',		$uid);
		      	$render->assign('uname',	pnUserGetVar('uname',$uid));
		    }
	    }
    }
    // assign data
    $render->assign('email',	pnModGetVar('UserDeletion','email'));
    $render->assign('authid',	Securityutil::generateAuthKey());

    // Return the output that has been generated by this function
    return $render->fetch('userdeletion_admin_main.htm');
}


?>