<?php
 
/**
 * the main user function
 * 
 * @return       output       The main module page
 */
function UserDeletion_user_main()
{
    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $pnRender =& new pnRender('UserDeletion');
	    
    // Return the output that has been generated by this function
    return $pnRender->fetch('userdeletion_user_main.htm');
}

/**
 * delete function
 * 
 * @return       output
 */
function UserDeletion_user_delete()
{
    if (!pnSecConfirmAuthKey() || !pnUserLoggedIn()) {
	pnSessionSetVar('errormsg',_USERDELETIONNOAUTH);
	return pnRedirect(pnModURL('UserDeletion','user','main'));
    }
    
    // call the delete-function
    return pnModAPIFunc('UserDeletion','user','delete');
}


?>